image: Visual Studio 2017
init:
  - git config --global core.autocrlf true
install:
  - ps: $env:BuildNumber= $env:APPVEYOR_BUILD_NUMBER
  - ps: $env:DOTNET_SKIP_FIRST_TIME_EXPERIENCE = true
  - ps: $env:NUGET_XMLDOC_MODE = "skip"
  - ps: $env:DOTNET_CLI_TELEMETRY_OPTOUT = 1
build_script:
  - dotnet --version
  - dotnet pack -c Release
test_script:
  - dotnet test .\test\Insql.Tests\Insql.Tests.csproj -c Release -f netcoreapp2.2
  - dotnet test .\test\Insql.Tests\Insql.Tests.csproj -c Release -f net461
